### ISSUE TITLE
incorrect NumPy in the Docker container

### ISSUE THREAD

**Issue by tromgy** [illustrated-series/deep-learning-illustrated#2]
Following the directions and running Docker as:

`sudo docker run -v $(pwd):/home/jovyan/work -it --rm -p 8888:8888 dli-stack` on MacOS 10.14.3, and then attempting to run a Jupyter notebook that uses `numpy`, e.g. "mnist_digit_pixel_by_pixel" results in the following error when importing `numpy`:

```
ImportError: Something is wrong with the numpy installation. While importing we detected an older version of numpy in ['/opt/conda/lib/python3.6/site-packages/numpy']. One method of fixing this is to repeatedly uninstall numpy until none is found, then reinstall this version.
```

I can run this notebook fine in my local virtual environment that I have setup manually, but the whole point of using Docker was to get the environment already setup. 🙁

**Comment by jonkrohn** [comment]
Ah, thanks @tromgy! I thought we'd fixed this one. I'm on it right now!

**Comment by jonkrohn** [comment]
Actually @tromgy ... can you please `git pull` to ensure you have the latest Dockerfile? We updated it three days ago in an effort to squash this bug.

**Comment by jonkrohn** [comment]
And then @tromgy ... If the Dockerfile updates as a result of the `git pull`, re-running steps eight, nine and ten of the [installation instructions](https://github.com/illustrated-series/deep-learning-illustrated/blob/master/installation/step_by_step_MacOSX_install.md) will hopefully do the trick. Please let me know 😄

**Comment by tromgy** [comment]
Thanks, @jonkrohn, update did fix the issue. In retrospect I should have checked the recent commit history before submitting the issue.

Anyways, thanks for the resolution, and I enjoy your book very much!

**Comment by jonkrohn** [comment]
Ah great @tromgy ! I'm glad it worked and that you've enjoyed the book so far :)
The remaining chapters should be available in Safari in the next few weeks!
